name: 'New Release'
description: 'Publish a new release to GitHub'

inputs:
  environment:
    description: 'The environment to deploy to'
    required: true

  ref:
    description: 'The Git ref to deploy'
    required: true

  github_token:
    description: 'The GitHub token to use'
    required: true

runs:
  using: 'composite'
  steps:
    # Get the current date and time in both human-readable and machine-readable formats
    # Human-readable should be "Thursday, 1 January 1970 00:00"
    - name: Get the date and time
      shell: bash
      id: get_date
      run: |
        echo "human_date=$(date +'%A, %d %B %Y %H:%M')" >> $GITHUB_OUTPUT
        echo "machine_date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

    # Create a Git tag with the environment name and machine-readable date
    - name: 🏷️ Tag version
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ inputs.github_token }}
        custom_tag: "${{ inputs.environment }}-${{ steps.get_date.outputs.machine_date }}"
        tag_prefix: ''

    # Get the artifact from the build job
    - name: 📥 Get artifact
      id: get_artifact
      uses: actions/download-artifact@v4
      with:
        name: public
        path: public

    - name: 📦 Zip artifact
      run: zip -r public.zip public
      shell: bash

    # If this is the main branch, create a release named after the github repo slug and the human readable date
    - name: 📦 Create release
      if: ${{ inputs.environment == 'production' }}
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ steps.tag_version.outputs.new_tag }}"
        artifacts: "public.zip"
        token: ${{ inputs.github_token }}
        makeLatest: true
        name: "${{ github.event.repository.name }} ${{ steps.get_date.outputs.human_date }}"
        body: |
          # ${{ inputs.environment }}

          ${{ steps.tag_version.outputs.changelog }}
