name: 🧹 Remove ZeroPoint branding
on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Project name for replacement'
        required: false
        default: ''
      author:
        description: 'Author name for replacement'
        required: false
        default: ''
      description:
        description: 'Project description'
        required: false
        default: ''

jobs:
  rebrand:
    runs-on: ubuntu-latest
    if: github.repository != 'MWDelaney/ZeroPoint'
    steps:

      - name: 📥 Checkout the repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: 🏷️ Run rebranding script
        run: node .github/scripts/zeropoint-rebrand.js --ci
        env:
          REBRAND_PROJECT_NAME: ${{ github.event.inputs.project_name }}
          REBRAND_AUTHOR: ${{ github.event.inputs.author }}
          REBRAND_DESCRIPTION: ${{ github.event.inputs.description }}

      - name: 🚀 Commit changes and delete this workflow
        uses: EndBug/add-and-commit@v9
        with:
          remove: '["./.github/workflows/zeropoint-rebrand.yml"]'
          message: "Up to zero 🪐"
          tag: 'v0.0.1 --force'
